version: '3.8' # Using a slightly newer version, 3.3+ supports depends_on conditions

services:
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

            - ELASTIC_PASSWORD=MyStrongPassword123!
            - xpack.security.enabled=true
            - xpack.security.authc.api_key.enabled=true
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - es01_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        healthcheck:
            test: ["CMD-SHELL", "curl -s --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -u elastic:YourStrongPassword123! https://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow\"' || curl -s -u elastic:MyStrongPassword123! http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow\"'"]
            interval: 10s
            timeout: 10s
            retries: 120

    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.28
        container_name: kibana
        ports:
            - 5601:5601
        environment:

            - ELASTICSEARCH_HOSTS=["http://es01:9200"]
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=MyStrongPassword123!
        volumes:
            - kibana_data:/usr/share/kibana/data
        depends_on:
            es01:
                condition: service_healthy

    nginx:
        image: luizpaulonievola/nginx-beats
        container_name: nginx_beats
        ports:
            - 9000:80
volumes:
    es01_data:
        driver: local
    kibana_data:
        driver: local