---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-app
  template: # A planta que diz ao deplyment como criar os pods
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: luizpaulonievola/flask-kub-proj
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer