global:
  scrape_interval: 15s
  scrape_timeout: 10s
  
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8585']

  - job_name: 'traefik'
    scrape_interval: 15s
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9101']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
